added option to log messages to terminal. default is false
pykale/pykale pull request #358
Opened 2023-04-03 16:24 UTC by Schobs

Fixes #{issue_number}.

### Description
Adds option to log to terminal. THis is useful since we want to avoid print statements, and in interactive examples it is important to print to terminal. This will not affect any existing code since it defaults to False.

### Status
**Ready**

If you've been given access to pykale with role Triage or above, on the right (delete these after selection):

- Select **one most appropriate** label.
- **When** your pull request is **ready** for review, select a reviewer. Use the suggested one if unsure.

If you cannot see an option to select a reviewer/label, that means one maintainer will get notified upon your pull request and then select for you.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [x ] In-line docstrings updated.
- [ ] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/main/docs/source) manually updated for new API.

2023-04-06 17:01 UTC, Mdnaimulislam approved these changes

2023-04-08 11:30 UTC, Mdnaimulislam reviewed
@Schobs Didn't pass all the checks.

2023-04-17 12:12 UTC, Mdnaimulislam approved these changes
All okay.

2023-04-17 14:13 UTC, haipinglu commented on kale/utils/logger.py
> +    if log_to_terminal:
@Schobs  Update https://github.com/pykale/pykale/blob/main/tests/utils/test_logger.py to test this option to improve the coverage.

2023-04-17 14:15 UTC, haipinglu requested changes
@Schobs Some minor changes needed before merging.

2023-05-18 10:59 UTC, Mdnaimulislam approved these changes
test_logger is coveraging 100% of logger. LGTM. Well done.

2023-05-18 11:11 UTC, haipinglu approved these changes

2023-05-18 11:49 UTC, merged