Support py3.10 and remove py3.7
pykale/pykale pull request #370
Opened 2023-04-28 17:11 UTC by Mdnaimulislam

Fixes #{368}.

### Description
Added new python version 3.10 and removed python version 3.7.

### Status
**Work in progress**

### Types of changes

- [ ] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] In-line docstrings updated.
- [ ] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/main/docs/source) manually updated for new API.

2023-04-29 18:07 UTC, XianyuanLiu commented
It seems that Python 3.10 costs much more time in dependency installation than 3.8 and 3.9.

2023-05-02 10:45 UTC, Mdnaimulislam reviewed
It looks like the sklearn package (not supported by Python 3.10) is being used by one of our dependencies. See this https://github.com/scikit-learn/sklearn-pypi-package, where it says to track down which dependency is using sklearn. I have tried to find it for the last couple of days but haven't been able to track it down. So, for the time being, I have set the environment variable SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error (as provided by the above URL I mentioned).

2023-05-02 13:53 UTC, XianyuanLiu requested changes
Thanks and well done! There are some minor enhancements. This bypassing may be tracked, and removed once it becomes unnecessary.

2023-05-02 13:53 UTC, XianyuanLiu commented on setup.py
> +# Set an environment variable to bypass the SKLEARN error message.
Please add the link to [sklearn-pypi-package](https://github.com/scikit-learn/sklearn-pypi-package#how-to-fix-the-error-for-the-main-use-cases) for further information, preventing those unfamiliar with this PR from getting confused about why this error was bypassed.

2023-05-02 14:15 UTC, Mdnaimulislam commented on .github/workflows/test.yml
>              python-version: "3.8"
Okay, keeping only the Python 3.10 for simplify the test process.

2023-05-02 15:13 UTC, Mdnaimulislam commented
I didn't have any idea that the error was being caused by the nilearn version. After my research, my assumption was that it was due to the setuptools version. I encountered a couple of places where the same problem arose because of setuptools. So yes, this problem is related to pip and setuptools. When I was trying to find the cause locally, I came across an error: "SetuptoolsDeprecation: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer." I am not entirely sure if this is connected to the problem we are having. I have changed the nilearn version; let's see if this solves our problem.

2023-05-02 16:28 UTC, XianyuanLiu commented
There are still some Python 3.7 usages in [workflow and description](https://github.com/search?q=repo%3Apykale%2Fpykale%203.7&type=code). We'd better update them.

2023-05-03 02:14 UTC, XianyuanLiu approved these changes
LGTM

2023-05-03 02:15 UTC, merged