Refactor resnet
pykale/pykale pull request #409
Opened 2023-10-03 11:12 UTC by wenruifan

### Description
- Refactor ResNet classes in image_cnn.py and add Flatten and Indentify modules.
- Add corresponding test code for new features.

### Status
**Ready**

If you've been given access to pykale with role Triage or above, on the right (delete these after selection):

- Select **one most appropriate** label.
- **When** your pull request is **ready** for review, select a reviewer. Use the suggested one if unsure.

If you cannot see an option to select a reviewer/label, that means one maintainer will get notified upon your pull request and then select for you.

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [x] In-line docstrings updated.
- [x] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/main/docs/source) manually updated for new API.

2023-10-03 19:43 UTC, xianyuanliu commented on kale/embed/image_cnn.py
> +    This module is to any unwanted layer sof pre-trained models with
Maybe typo: sof

2023-10-03 19:58 UTC, xianyuanliu approved these changes
Nice simplification! Others need to review and align related work with this improvement.

2023-10-03 19:58 UTC, xianyuanliu commented on kale/embed/image_cnn.py
> +    This module is to any unwanted layer sof pre-trained models with
This module is to replace any unwanted layer of pre-trained models with

2023-10-04 15:06 UTC, haipinglu commented on kale/embed/image_cnn.py
> +        >>> x = Flatten()(x)
Should this be `Flatten(x)` instead?

2023-10-04 15:08 UTC, haipinglu commented on kale/embed/image_cnn.py
> +    tensor to 2D vector, which is (B, N). B is the batch size and N is the product of all dimensions except batch size.
Missing articles (English)
a 2D vector
except the batch size

2023-10-04 15:10 UTC, haipinglu commented on kale/embed/image_cnn.py
> +    This module is to replace an unwanted layers of the pre-trained model with an identity layer.
English: an (singular)  .... layers (plural)?

2023-10-04 15:11 UTC, haipinglu commented on kale/embed/image_cnn.py
> +    It returns the input tensor as output.
the output

2023-10-04 15:22 UTC, haipinglu requested changes
Some minor English problems to fix before merging. 
Also, clarify the ToDos in the description please.

2023-10-04 15:57 UTC, haipinglu approved these changes
Well done!

2023-10-04 16:30 UTC, merged