Change testing data directory paths
pykale/pykale pull request #415
Opened 2023-10-13 20:42 UTC by wang-hlin

Fixes #412.

### Description
Some testing data were not downloaded into `pykale/tests` while running `pytest`. 
  
`tests/loaddata/test_video_access.py`, `tests/pipeline/test_video_domain_adapter.py` and `tests/utils/test_download.py` directory paths have been changed to `pykale/tests/test_data`.  
  
Logs and trainer outputs from `tests/helpers/pipe_test_helper.py`, `tests/pipeline/test_deepdta.py`, `tests/pipeline/test_multiomics_trainer.py` and `tests/utils/test_logger.py` have been changed to `pykale/tests/outputs`.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] In-line docstrings updated.
- [ ] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/main/docs/source) manually updated for new API.

2023-10-17 18:12 UTC, xianyuanliu requested changes
@alanbijuthomas Please review this.

2023-10-23 10:50 UTC, alanbijuthomas commented
Looks good to me

2023-10-23 10:50 UTC, alanbijuthomas approved these changes

2023-10-23 13:25 UTC, xianyuanliu approved these changes
LGTM

2023-10-23 13:25 UTC, merged