Split the test data downloading and test cases
pykale/pykale pull request #424
Opened 2023-11-15 13:34 UTC by wang-hlin

Fixes #419.

### Description
Split the code for downloading into `tests/test_data.py`. All downloaded data will be stored in the `test/test_data` directory. Some files will still be generated in the `test_data` folder while running `pytest`, as a result of data preprocessing.

Use `cfg.DATASET.DOWNLOAD` to control the download process in the `get_cifar` function located in `kale/loaddata/image_access.py`.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] In-line docstrings updated.
- [ ] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/main/docs/source) manually updated for new API.

2023-11-15 18:36 UTC, xianyuanliu requested changes
@wenruifan Please conduct a review.

2023-11-16 10:34 UTC, wenruifan requested changes
Good work with just some minor places to change.

2023-11-20 10:50 UTC, wenruifan approved these changes
Nice work.

2023-11-23 22:20 UTC, xianyuanliu requested changes

2023-11-23 22:20 UTC, xianyuanliu commented on tests/test_data.py
> +# tests/conftest.py
The comments are not clear. Please use a consistent format throughout, e.g. 'Downloading gait gallery data for tests/conftest.py test'. Please change all the comments below.

2023-11-23 22:20 UTC, xianyuanliu commented on tests/test_data.py
> +office_path = str(Path(path_test_data) / "office")
Is this still 'downloading CMR dataset'?

2023-11-23 22:20 UTC, xianyuanliu commented on tests/test_data.py
> +datasets.MNIST(path_test_data, train=True, transform=get_transform("mnistm"), download=True)
Is this still 'downloading CMR dataset'?

2023-11-23 22:20 UTC, xianyuanliu commented on tests/test_data.py
> +office_path = str(Path(path_test_data) / "office")
Please put this line above the office data downloading.

2023-11-24 17:06 UTC, xianyuanliu approved these changes
Well done. Please proceed with implementing data caching for downloads in GitHub Actions.

2023-11-24 17:06 UTC, merged