Refine test Readme
pykale/pykale pull request #432
Opened 2024-01-09 21:01 UTC by xianyuanliu

### Description
This is an update to the Readme for the test, reflecting the newly implemented test workflow and the GitHub Actions Cache system.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] In-line docstrings updated.
- [ ] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/main/docs/source) manually updated for new API.

2024-01-09 21:47 UTC, haipinglu commented on tests/README.md
> +The test pipeline is defined in [`pykale/.github/workflows/test.yml`](https://github.com/pykale/pykale/blob/main/.github/workflows/test.yml). It is triggered on every pull request, push to the main b
say UK time

2024-01-09 21:48 UTC, haipinglu commented on tests/README.md
> +The test pipeline is defined in [`pykale/.github/workflows/test.yml`](https://github.com/pykale/pykale/blob/main/.github/workflows/test.yml). It is triggered on every pull request, push to the main b
It is triggered on every pull request and every push to the main branch, and we also run it at midnight (UK time) each day.

2024-01-09 21:50 UTC, haipinglu commented on tests/README.md
> +To minimise additional downloading time, test data and pip packages once downloaded are stored in the [GitHub Actions Caches](https://github.com/pykale/pykale/actions/caches) for future reuse. Test d
minimise -->minimize
once downloaded --> ,  once downloaded, (comma to separate)

2024-01-09 21:51 UTC, haipinglu requested changes
Minor English problems to fix before merging. Thanks.

2024-01-09 23:55 UTC, xianyuanliu commented
> Minor English problems to fix before merging. Thanks.

Thanks for pointing out the issues. I have made the corrections.

2024-01-10 08:10 UTC, haipinglu approved these changes

2024-01-10 08:10 UTC, merged