402 refactor merge modules losses distance and metrics to one
pykale/pykale pull request #441
Opened 2024-07-08 11:02 UTC by shuo-zhou

Fixes #402.

### Description
Merge modules `losses`,  `distance`, and `metrics` to one under `evaluate`.

### Status
**Ready/Work in progress/Hold**

### Types of changes

- [ ] Non-breaking change (fix or new feature that would not break existing functionality).
- [x] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] In-line docstrings updated.
- [x] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/main/docs/source) manually updated for new API.

2024-08-05 15:09 UTC, jiayang-zhang reviewed
Review completed.

2024-08-05 15:09 UTC, jiayang-zhang commented on tests/evaluate/test_metrics.py
Yes, I can confirm the code added to this file -- as it is the exact code from `tests/utils/test_distance.py` (which is now deleted).

2024-08-05 15:09 UTC, jiayang-zhang commented on tests/utils/test_distance.py
Yes, I can confirm the file deletion -- as the exact code has been transferred to `tests/evaluate/test_metrics.py`.

2024-09-19 14:29 UTC, wenruifan commented on examples/fewshot_protonet/README.md
I can confirm it. It is a typo. It should be `kale.predict.losses.protonet_loss`.

2024-09-19 15:31 UTC, alanbijuthomas requested changes
Only a minor change required - renaming of a test function.

2024-09-19 15:31 UTC, alanbijuthomas commented on tests/evaluate/test_metrics.py
> +
Rename test_proto_loss to test_protonet_loss.

2024-09-24 15:52 UTC, merged